export enum EVENTS {
  NEW_USER_CREATED = 'NEW_USER_CREATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  NEW_REQUEST_CREATED = 'NEW_REQUEST_CREATED',
  NEW_NOTIFICATION = 'NEW_NOTIFICATION',
  NEW_EMAIL_NOTIFICATION = 'NEW_EMAIL_NOTIFICATION',
  NEW_CODE_GENERATED = 'NEW_CODE_GENERATED',
}
